### ISSUE TITLE
J&R: Spieler zurücksetzen 

### ISSUE THREAD

**Issue by D3nnisK** [inBrainMeDiDa/WG_Held#4]
Die Spielfigur soll an den Levelanfang zurückgesetzt werden, wenn sie aus dem Level fällt oder anderweitig am Fortschritt gehindert wird. Der aktuelle Level soll dabei nicht zurückgesetzt werden.

**Comment by Rodario** [comment]
Habe länger dran rumgeknobelt und bin bei der einfachen Lösung hängen geblieben. Eine Entity unter dem Level die den Spieler wieder zum start wirft.

**Comment by D3nnisK** [comment]
Wenn der Spieler zum Start zurückgeworfen wird, werden auch alle Dokumente neu erzeugt, der Punktestand bleibt aber gleich.

**Comment by Rodario** [comment]
Habe eine "Respawn Entity" erstellt die man in Tiled erzeugt und dieser dort mit posX bzw. posY die Koordinaten für den Rücksetzpunkt mitgibt. Dokumente werden nicht mehr neu geladen.
